.golangci.yml, .prow.yaml, Makefile
- adds support for running unit tests inside of containers, generates html output file to visualize code coverage by tests
- adds support for running golangci-lint inside of containers (https://golangci-lint.run/)
- adds support for running gosec inside of containers (https://github.com/securego/gosec)
=> adds support for unit tests, golangci-lint and gosec

krm-functions/lib/kubeobject/kubeobject.go
SDK functions will utilize the already parsed YAML nodes inside the KubeObject, and thus they are more efficient in case of GetGoStruct().
Otherwise I propose to reuse upstream SDK functions, instead of reimplementing them.
=> Avoid YAML marshaling round-trips and use existing upstream SDK functions

krm-functions/lib/test/helpers.go, krm-functions/lib/test/krm_fn.go, krm-functions/lib/test/kubeobject.go
Moving the helper functions that proved to be useful while testing dnn-fn to a common test lib
=> Add helper functions for testing KRM functions

krm-functions/lib/interface/v1alpha1/interface.go, krm-functions/lib/interface/v1alpha1/interface_test.go, krm-functions/lib/ipalloc/v1alpha1/ipalloc.go, krm-functions/lib/ipalloc/v1alpha1/ipalloc_test.go, krm-functions/lib/kubeobject/kubeobject.go, krm-functions/lib/kubeobject/kubeobject_test.go, krm-functions/lib/vlanalloc/v1alpha1/vlanalloc.go, krm-functions/lib/vlanalloc/v1alpha1/vlanalloc_test.go
- Rename SetSpec and SetStatus Implementations
- Validate type parameter (T1)
- Refactor libs to match the new KubeObjectExt API
The type parameter validation will only allow struct types to be used as the KubeObjectExt[T1] type parameter, however all structs are passed by pointers in all methods.
=> Add type-safety to KubeObjectExt in a non-backward compatible manner

krm-functions/lib/test/krm_fn.go
Fixes https://github.com/nephio-project/nephio/issues/165
=> KRM function pipeline test lib: put input kpt package and expected data into separate subdirectories

operators/nephio-controller-manager/go.mod, operators/nephio-controller-manager/go.sum
The last PR merged, so now the changes to pkg are available for consumption by the separate operator module. Change the operator module to use those.
This is not great, we should figure out a better package structure, or figure out Go workspaces.
=> Use regular build, without the replace

operators/nephio-controller-manager/go.mod, operators/nephio-controller-manager/go.sum
In order for the automated docker build to work, we need to comment out the replace line.
Merging this will trigger the docker build and push the image to our registry.
Alternatively, instead of merging this we can any of these:
- Manually build and push
- Fix the docker build in the nephio-controller-manager to copy in the entire controllers directory and tweak the replace statement
- Figure out something better than the way we do our multiple go.mod files right now
=> Remove replace in go.mod

Makefile, controllers/pkg/Makefile, default-docker.mk, default-go-lint.mk, default-go-misc.mk, default-go-test.mk, default-go.mk, default-gosec.mk, default-help.mk, krm-functions/Makefile, krm-functions/dnn-fn/Makefile, krm-functions/interface-fn/Makefile, krm-functions/ipam-fn/Makefile, krm-functions/lib/Makefile, krm-functions/nad-fn/Makefile, krm-functions/nfdeploy-fn/Makefile, krm-functions/nfdeploy-fn/amfdeployfn/Makefile, krm-functions/nfdeploy-fn/smfdeployfn/Makefile, krm-functions/nfdeploy-fn/upfdeployfn/Makefile, krm-functions/pipeline-tests/Makefile, krm-functions/vlan-fn/Makefile, operators/nephio-controller-manager/Makefile
The most important fix is that `make test` didn't fail in krm-functions/Makefile if one of the sub-make tests failed
=> Minor fixes and cosmetics around Makefiles

controllers/pkg/reconcilers/approval/reconciler.go, controllers/pkg/reconcilers/approval/reconciler_test.go
There is now no longer a default delay; it only delays if you specifically give a delay annotation.
The minimum delay is now 0.
Re-ordered the checks so that the delay will not come into play unless all other checks are already met.
Added some tests.
=> Faster approvals for the auto-approve controller

controllers/pkg/porch/condition/condition_test.go, controllers/pkg/reconcilers/approval/reconciler_test.go, controllers/pkg/reconcilers/bootstrap-packages/reconciler_test.go, controllers/pkg/reconcilers/bootstrap-secret/README.md, controllers/pkg/reconcilers/bootstrap-secret/reconciler.go
Removed the dependency to configsync namespace, but we need to see if the namespace is to be set.
=> removed configsync dependency

krm-functions/nfdeploy-fn/fn/function.go, krm-functions/nfdeploy-fn/fn/helper.go, krm-functions/nfdeploy-fn/fn/testdata/golden/nfdeployment_witthduplicatedependency/Kptfile, krm-functions/nfdeploy-fn/fn/testdata/golden/nfdeployment_witthduplicatedependency/_expected.yaml, krm-functions/nfdeploy-fn/fn/testdata/golden/nfdeployment_witthduplicatedependency/capacity.yaml, krm-functions/nfdeploy-fn/fn/testdata/golden/nfdeployment_witthduplicatedependency/dependency.yaml, krm-functions/nfdeploy-fn/fn/testdata/golden/nfdeployment_witthduplicatedependency/dependency_1.yaml, krm-functions/nfdeploy-fn/fn/testdata/golden/nfdeployment_witthduplicatedependency/dnn.yaml, krm-functions/nfdeploy-fn/fn/testdata/golden/nfdeployment_witthduplicatedependency/interface-n2.yaml, krm-functions/nfdeploy-fn/fn/testdata/golden/nfdeployment_witthduplicatedependency/nfdeployment.yaml, krm-functions/nfdeploy-fn/fn/testdata/golden/nfdeployment_witthduplicatedependency/workload_cluster.yaml, krm-functions/pipeline-tests/pipeline_test.go
These changes will ensure we have nf deploy fn to apply de dupulication logic to NF Deploy Param Ref
1. Changes to Add Dependency to check if it already exist before adding. Thanks @gvbalaji for the code snippet in chat.
2. Added test cases to handle dependency, if same file is present multiple times. Its not in our use case, but its better to add that too.
3. Added changes to pipeline tests to ensure, if I run the NF Deploy Fn multiples after that, it doesn't break the idempotency principle.
Docker image I used for testing - [docker.io/lostbrain/nfdeployfn:test-5](http://docker.io/lostbrain/nfdeployfn:test-5)
=> De duplication logic to NF Deploy Fn Param Ref

controllers/pkg/porch/condition/condition_test.go
This change is to add 100% code coverage in Porch condition.go.
=> 100% test-code-coverage for condition.go

controllers/pkg/giteaclient/giteaclient.go
This change removes a conditional statement which is never executed.
=> Add comments for singleInstance creation mechanism in giteaclient.go 

.prow.yaml
golangci-lint update to work with go 1.22 updated other components as well
This resolves failing tests in https://github.com/nephio-project/nephio/pull/597 and https://github.com/nephio-project/nephio/pull/722
=> Bumping gotests image version to next build

.golangci.yml, default-go-lint.mk
Golangci-lint config syntax has changed in recent version, this removes warning messages from logs:
```
level=warning msg="[config_reader] The configuration option `run.skip-files` is deprecated, please use `issues.exclude-files`."
level=warning msg="[config_reader] The configuration option `run.skip-dirs` is deprecated, please use `issues.exclude-dirs`."
```
Timeout is now config defined not command-line switch
=> Modernizing golangci-lint configuration for latest version syntax

.github/workflows/codeql.yaml
CodeQL default setup has been causing problems by not recognising golang, adding manual configuration.
=> Manual CodeQL configuration to mitigate tide merging problems

.clomonitor.yml, README.md
This PR adds SBOM information to README as well as [CLOMonitor](https://github.com/cncf/clomonitor) exemption configuration. This resolves https://github.com/nephio-project/nephio/issues/551 and https://github.com/nephio-project/nephio/issues/546
=> SBOM and license scanning information and monitor fixes

.github/workflows/codeql.yaml
This PR will harden CodeQL workflow by pinning actions to digests, restricting token rights and executing runner hardener.
=> Hardening codeql workflow

controllers/pkg/reconcilers/approval/reconciler.go, controllers/pkg/reconcilers/config/config.go, operators/nephio-controller-manager/main.go
Change approval controller PR Get to hit the api directly instead of reading from local cache.
Adjust the reque duration to prevent race condition.
During debugging the approval delay issue reported [here](https://github.com/nephio-project/nephio/issues/462) it became apparent that the packagerev being fetched was a cached version which didn't get updated for quite some time.
To circumvent this, we are retrieving the PR using the apiReader interface which bypasses the local cache and hits the k8s api directly.
=> Improve approval reconciler timings

krm-functions/nfdeploy-fn/fn/function.go, krm-functions/nfdeploy-fn/fn/helper.go, krm-functions/nfdeploy-fn/fn/testdata/golden/nfdeployment_witthduplicatedependency/Kptfile, krm-functions/nfdeploy-fn/fn/testdata/golden/nfdeployment_witthduplicatedependency/_expected.yaml, krm-functions/nfdeploy-fn/fn/testdata/golden/nfdeployment_witthduplicatedependency/capacity.yaml, krm-functions/nfdeploy-fn/fn/testdata/golden/nfdeployment_witthduplicatedependency/dependency.yaml, krm-functions/nfdeploy-fn/fn/testdata/golden/nfdeployment_witthduplicatedependency/dependency_1.yaml, krm-functions/nfdeploy-fn/fn/testdata/golden/nfdeployment_witthduplicatedependency/dnn.yaml, krm-functions/nfdeploy-fn/fn/testdata/golden/nfdeployment_witthduplicatedependency/interface-n2.yaml, krm-functions/nfdeploy-fn/fn/testdata/golden/nfdeployment_witthduplicatedependency/nfdeployment.yaml, krm-functions/nfdeploy-fn/fn/testdata/golden/nfdeployment_witthduplicatedependency/workload_cluster.yaml
Solves #493 
These changes will ensure we have nf deploy fn to apply de dupulication logic to NF Deploy Param Ref
1. Changes to Add Dependency to check if it already exist before adding. Thanks @gvbalaji for the code snippet in chat.
2. Added test cases to handle dependency, if same file is present multiple times. Its not in our use case, but its better to add that too.
3. Added changes to pipeline tests to ensure, if I run the NF Deploy Fn multiples after that, it doesn't break the idempotency principle.
=> De duplication logic to NF Deploy Fn Param Ref (#494)

operators/o2ims-operator/Dockerfile, operators/o2ims-operator/README.md
This PR updates the Dockerfile to run `kopf` as non-root. It also updates the README to reflect the correct container image being used.
=> updates the dockerfile to run kopf as nonroot

.gitignore, operators/o2ims-operator/Dockerfile, operators/o2ims-operator/Makefile, operators/o2ims-operator/README.md, operators/o2ims-operator/tox.ini
Add Makefile docker target.
Update tox and README
=> Add makefile for o2ims

operators/o2ims-operator/controllers/utils.py
Update the o2ims operator so that it requests creation of PackageVariants of upstream packages with integer rather than string revisions.
This change has been tested locally and with this change, the o2ims tests will run correctly.
=> Update o2ims operator for integer revisions

controllers/pkg/reconcilers/generic-specializer/reconciler.go
As part of the free5gc test 008, we copy, pull, mutate, push a UPF pkg.
https://github.com/nephio-project/test-infra/blob/main/e2e/tests/free5gc/008.sh#L53
The push fails due to the generic specializer continuously trying to update the claims on the relevant resources.
The reconciler itself needs to be reworked properly to address the issue and determine when it is "finished"
For now, this is a quick fix to get the test suite passing.
=> Fix generic specializer infinite loop
