nephio-project/nephio

.gitignore, .spellcheck.yml, .wordlist.txt, README.md, tox.ini
This tool helps to detect typos in markdown files
=> Enable spellcheck

krm-functions/lib/kubeobject/kubeobject.go, krm-functions/lib/kubeobject/kubeobject_test.go
@henderiw was concerned with the lack of static type checking in KubeObjectExt, and I agree. This is what this PR tries to fix by adding static type checking to NewFromGoStruct, SetSpec and SetStatus.
For backward compatibility reasons, the original SetSpec and SetStatus methods were kept, and the new methods were added as SafeSetSpec and SafeSetStatus.
=> Add static type checking for KubeObjectExt methods

krm-functions/lib/kptrl/kptrl.go, krm-functions/lib/kptrl/kptrl_test.go
this is an extension to the resource list library to be able to retrieve the resourcelist from the package revisions.
This allows to reuse the framework of conditions sdk and fn in th specialiser controllers.
=> resourcelist get

krm-functions/dnn-fn/fn/function.go, krm-functions/interface-fn/fn/function.go, krm-functions/ipam-fn/fn/function.go, krm-functions/nad-fn/mutator/mutator.go, krm-functions/vlan-fn/fn/function.go
Return err on `condsdk.New` returns error on setting up sdk. Also avoid further execution on error.
=> Return err on `condsdk.New` returns error

operators/nephio-controller-manager/go.mod, operators/nephio-controller-manager/go.sum, operators/nephio-controller-manager/main.go
added the package and secret bootstrapped to nephio operator
=> added bootstrappers

krm-functions/dnn-fn/fn/function.go, krm-functions/dnn-fn/fn/testdata/create_owned_resources/_expected.yaml, krm-functions/dnn-fn/go.mod, krm-functions/dnn-fn/go.sum, krm-functions/interface-fn/fn/function.go, krm-functions/interface-fn/fn/testdata/interface_cni_novlan/_expected.yaml, krm-functions/interface-fn/fn/testdata/interface_cni_vlan-dualstack/_expected.yaml, krm-functions/interface-fn/fn/testdata/interface_cni_vlan-ipv6only/_expected.yaml, krm-functions/interface-fn/fn/testdata/interface_cni_vlan/_expected.yaml, krm-functions/interface-fn/fn/testdata/interface_loopback/_expected.yaml, krm-functions/interface-fn/go.mod, krm-functions/interface-fn/go.sum, krm-functions/nad-fn/go.mod, krm-functions/nad-fn/go.sum, krm-functions/nfdeploy-fn/go.mod, krm-functions/nfdeploy-fn/go.sum, krm-functions/pipeline-tests/go.mod, krm-functions/pipeline-tests/go.sum, krm-functions/pipeline-tests/testdata/real_deployment/_expected.yaml, krm-functions/pipeline-tests/testdata/real_deployment_2/_expected.yaml, krm-functions/pipeline-tests/testdata/simplified_deployment/_expected.yaml
this PR updates go mod aligning with the latest lib updates in the api library
=> aligned with check in api where example is seen as unitialized now

krm-functions/nad-fn/fn/function.go, krm-functions/nad-fn/fn/testdata/default_network/_expected.yaml, krm-functions/nad-fn/fn/testdata/empty_ipamaddress/_expected.yaml, krm-functions/nad-fn/fn/testdata/golden/create_full_resources/_expected.yaml, krm-functions/nad-fn/fn/testdata/golden/create_full_resources_dual_stack/_expected.yaml, krm-functions/nad-fn/fn/testdata/golden/create_full_resources_dual_stack_redundant/_expected.yaml, krm-functions/nad-fn/fn/testdata/golden/create_full_resources_ipv6/_expected.yaml, krm-functions/nad-fn/fn/testdata/golden/empty_nad_masterinterface/_expected.yaml, krm-functions/nad-fn/fn/testdata/golden/existing_nad_resources/_expected.yaml, krm-functions/nad-fn/fn/testdata/golden/existing_nad_resources/nad-n3.yaml, krm-functions/nad-fn/fn/testdata/golden/existing_nad_resources/nad-n4.yaml, krm-functions/nad-fn/fn/testdata/golden/existing_nad_resources/nad-n6.yaml, krm-functions/nad-fn/fn/testdata/golden/ipallocation_notReady/_expected.yaml, krm-functions/nad-fn/fn/testdata/golden/only_ipallocation_ipvlanType/_expected.yaml, krm-functions/nad-fn/fn/testdata/golden/only_ipallocation_macvlanType/_expected.yaml, krm-functions/nad-fn/fn/testdata/golden/only_ipallocation_sriovType/_expected.yaml, krm-functions/nad-fn/fn/testdata/golden/only_vlanallocation/_expected.yaml, krm-functions/nad-fn/fn/testdata/golden/vlanallocation_notReady/_expected.yaml, krm-functions/pipeline-tests/testdata/real_deployment/_expected.yaml, krm-functions/pipeline-tests/testdata/real_deployment_2/_expected.yaml, krm-functions/pipeline-tests/testdata/simplified_deployment/_expected.yaml
Add a default namespace to NADs when creating the, so set-namespace will act upon them.
=> Create NADs with a namespace

controllers/pkg/go.mod, controllers/pkg/go.sum, krm-functions/configinject-fn/go.mod, krm-functions/configinject-fn/go.sum, krm-functions/interface-fn/fn/function.go, krm-functions/interface-fn/fn/testdata/interface_cni_vlan-dualstack/_expected.yaml, krm-functions/interface-fn/fn/testdata/interface_cni_vlan-dualstack/interface.yaml, krm-functions/interface-fn/fn/testdata/interface_cni_vlan-ipv6only/_expected.yaml, krm-functions/interface-fn/fn/testdata/interface_cni_vlan-ipv6only/interface.yaml, operators/nephio-controller-manager/go.mod, operators/nephio-controller-manager/go.sum
added network selection for n2/n3
- fix network controller
- update interface-fn
=> network selection

controllers/pkg/reconcilers/generic-specializer/reconciler.go, krm-functions/configinject-fn/fn/function.go
updated ocnfiginject to only take into account published packages
=> updated configinject to only take into account published packages

krm-functions/configinject-fn/fn/function.go
wrong comparison for the pr map
=> fixed comparison

krm-functions/ueransim-deploy-fn/fn/function.go, krm-functions/ueransim-deploy-fn/fn/template-cm.go, krm-functions/ueransim-deploy-fn/fn/template-nad.go
this ensures the ueransim fn is providing the right ctx for NAD/specialization
=> changed templating + annotation in pod template

krm-functions/nfdeploy-fn/common/function.go, krm-functions/nfdeploy-fn/smfdeployfn/testdata/createsmfdeployment/_expected.yaml, krm-functions/nfdeploy-fn/upfdeployfn/testdata/golden/createupfdeployment_stage2/_expected.yaml, krm-functions/pipeline-tests/testdata/real_deployment/_expected.yaml, krm-functions/pipeline-tests/testdata/real_deployment_2/_expected.yaml, krm-functions/pipeline-tests/testdata/simplified_deployment/_expected.yaml
dnn mapping was taking network instance iso din name
=> fixed dnn mapping

.prow.yaml
=> gotests version bump

.prow.yaml
Fix for recent changes in scanner tag of Fossology image
=> Fix for fossology scans

controllers/pkg/porch/condition/condition.go, controllers/pkg/porch/condition/condition_test.go
Add unit tests to condition module.
94%
=> Add unit tests for porch.condition

controllers/pkg/reconcilers/repository/reconciler.go
=> Optimize logging for repo controller

controllers/pkg/reconcilers/approval/reconciler.go, controllers/pkg/reconcilers/bootstrap-packages/reconciler.go, controllers/pkg/reconcilers/bootstrap-packages/reconciler_test.go, controllers/pkg/reconcilers/bootstrap-secret/reconciler.go, controllers/pkg/reconcilers/generic-specializer/reconciler.go, controllers/pkg/reconcilers/ipam-specializer/reconciler.go, controllers/pkg/reconcilers/network/reconciler.go, controllers/pkg/reconcilers/network/watch_endpoint.go, controllers/pkg/reconcilers/network/watch_node.go, controllers/pkg/reconcilers/token/reconciler.go, controllers/pkg/reconcilers/vlan-specializer/reconciler.go
Log from context on all reconcilers
=> Refactor logging for reconcilers

krm-functions/nfdeploy-fn/fn/function.go, krm-functions/nfdeploy-fn/fn/testdata/golden/nfdeployment_withexistingconfig/Kptfile, krm-functions/nfdeploy-fn/fn/testdata/golden/nfdeployment_withexistingconfig/_expected.yaml, krm-functions/nfdeploy-fn/fn/testdata/golden/nfdeployment_withexistingconfig/capacity.yaml, krm-functions/nfdeploy-fn/fn/testdata/golden/nfdeployment_withexistingconfig/dependency-1.yaml, krm-functions/nfdeploy-fn/fn/testdata/golden/nfdeployment_withexistingconfig/dependency.yaml, krm-functions/nfdeploy-fn/fn/testdata/golden/nfdeployment_withexistingconfig/dnn.yaml, krm-functions/nfdeploy-fn/fn/testdata/golden/nfdeployment_withexistingconfig/interface-n2.yaml, krm-functions/nfdeploy-fn/fn/testdata/golden/nfdeployment_withexistingconfig/nfdeployment.yaml, krm-functions/nfdeploy-fn/fn/testdata/golden/nfdeployment_withexistingconfig/workload_cluster.yaml
Tests done
1. Test with pre-existing config ref. *Done*
=> Allow pre existing config ref in NFDeployment

controllers/pkg/go.mod, controllers/pkg/go.sum, krm-functions/configinject-fn/go.mod, krm-functions/configinject-fn/go.sum, krm-functions/dnn-fn/go.mod, krm-functions/dnn-fn/go.sum, krm-functions/interface-fn/go.mod, krm-functions/interface-fn/go.sum, krm-functions/nad-fn/go.mod, krm-functions/nad-fn/go.sum, krm-functions/nfdeploy-fn/fn/function.go, krm-functions/nfdeploy-fn/fn/helper.go, krm-functions/nfdeploy-fn/go.mod, krm-functions/nfdeploy-fn/go.sum, krm-functions/pipeline-tests/go.mod, krm-functions/pipeline-tests/go.sum, krm-functions/ueransim-deploy-fn/go.mod, krm-functions/ueransim-deploy-fn/go.sum, operators/nephio-controller-manager/go.mod, operators/nephio-controller-manager/go.sum
=> aligned the core repo with api repo

.github/workflows/openssf_scorecard.yaml
This PR adds the OSSF scorecard action, which will help to analyze the codebase of Nephio to make sure that the codebase is complaint with OSSF best practices.
=> added scorecard action for OSSF

controllers/pkg/reconcilers/bootstrap-packages/reconciler.go
the change we did together cluster clients from secrets was wrong. Fix to handle this
=> update secret handling for cluster client

.prow.yaml
Dependency for pre-submit testing PRs:  https://github.com/nephio-project/nephio/issues/373
=> Adding pre-submit images build

README.md
Added banner for godoc and license in README.md .
=> Banner for godoc and license

CONTRIBUTING.md
created CONTRIBUTING.md file to improve the contributing process for new comers.
closes #545
=> (docs): added contributing.md file

README.md
added ossf best practices badge.
closes #548
=> (docs): ossf best practices badge

.github/dependabot.yml
Added dependabot as a dependency updation tool.
Closes #550
=> (feat): added dependabot

.prow.yaml
Builds dev image for: https://github.com/nephio-project/nephio/pull/844
=> O2 IMS Operator dev image build

.prow.yaml
Prow docker build job for the following - https://github.com/nephio-project/nephio/pull/849
=> Add prow docker build job for focom operator image

.prow.yaml
Fixing context path for Focom and O2IMS operators
=> Fixing context path for Focom and O2IMS operators

.github/ISSUE_TEMPLATE/bug_report.yaml
Adding a bug report template for the Nephio Project
=> Add bug_report issue template

.github/workflows/codeql.yaml, .prow.yaml
Change prow jobs to only run if changed on:
run_if_changed: "(\\.go|Makefile|\\.mk)$"
=> Refine pre and post submit job runs

operators/o2ims-operator/Dockerfile, operators/o2ims-operator/Makefile
Attempted fix for failing prow job - https://storage.googleapis.com/prow-nephio-sig-release/logs/build-push-o2-ims-operator-dev-image/1918582475521527808/build-log.txt
=> Fix o2ims docker dev image build

.prow.yaml, gitops-tools/kpt-argocd-cmp/kpt-render/Makefile, gitops-tools/kpt-argocd-cmp/kpt-repo/Makefile, gitops-tools/kpt-argocd-cmp/patch.sh
To align with https://github.com/nephio-project/test-infra/pull/352/files
=> Rename kpt-argo plugins

krm-functions/configinject-fn/Dockerfile, krm-functions/dnn-fn/Dockerfile, krm-functions/gen-configmap-fn/Dockerfile, krm-functions/gen-kustomize-res/Dockerfile, krm-functions/interface-fn/Dockerfile, krm-functions/ipam-fn/Dockerfile, krm-functions/nad-fn/Dockerfile, krm-functions/nfdeploy-fn/Dockerfile, krm-functions/ueransim-deploy-fn/Dockerfile, krm-functions/vlan-fn/Dockerfile, operators/focom-operator/Dockerfile, operators/nephio-controller-manager/Dockerfile
Missed the update of base docker images to align with go.mod
=> Update docker golang to 1.23.8

gitops-tools/kpt-argocd-cmp/kpt-render/Dockerfile, gitops-tools/kpt-argocd-cmp/kpt-repo/Dockerfile
Missed a few Docker file golang updates
=> Update missed Docker to 1.23.8
